frame_id: base
initial_x: 0.248
initial_y: -0.051
initial_z: 0.572
initial_orientation: [-0.679, 0.685, -0.153, 0.213]
# - Translation: [0.253, -0.004, 0.563]
# - Rotation: in Quaternion [-0.679, 0.685, -0.153, 0.213]
#             in RPY (radian) [-2.616, 0.085, -1.557]
#             in RPY (degree) [-149.881, 4.843, -89.196]
# rosrun tf tf_echo /base /realsense_torso_color_optical_frame
# Translation: [0.248, -0.051, 0.572]
# Rotation: in Quaternion [-0.679, 0.685, -0.153, 0.213]
#            in RPY (radian) [-2.617, 0.084, -1.557]
#            in RPY (degree) [-149.926, 4.825, -89.207]
